### ISSUE TITLE
Integrate gatsby-source-meetup

### ISSUE THREAD

**Issue by lannonbr** [syracuseio/syracuseio#2]
Given all of the events are up on meetup.com, we could use their API using [gatsby-source-meetup](https://github.com/phacks/gatsby-source-meetup) to load in the content from our meetup group into the site at build time.

**Comment by lannonbr** [comment]
With this, we could as well set up maybe a function on AWS Lambda to trigger builds on Netlify on a daily basis so the content on the site is fairly up to date with the content on meetup

**Comment by vormwald** [comment]
Keeping the site up to date is a big priority, so I love the idea of a daily rebuild. Maybe the lambda thing should be its own issue?

**Comment by lannonbr** [comment]
Sure, let me spin off another issue
