### ISSUE TITLE
Examine Styling architecture

### ISSUE THREAD

**Issue by lannonbr** [syracuseio/syracuseio#3]
Are we planning on staying consistent with the old site or updating the design?

As well, we can possibly look into using a CSS-in-JS framework to simplify the CSS written for the site. I tend to use Styled Components personally but we can examine other options as well.

**Comment by vormwald** [comment]
I'd like to keep it as similar as possible. To show the differences between the site in huge / gatsby.  We're using Styled Components at work, so I'm good with that solution 👍

**Comment by lannonbr** [comment]
Styled-components now is in the repo but I will keep this issue open until the design for the new site is fairly similar to the hugo site.

**Comment by lannonbr** [comment]
This is resolved. Closing. All future styles will be done with Styled Components.
