### ISSUE TITLE
Setup daily builds

### ISSUE THREAD

**Issue by lannonbr** [syracuseio/syracuseio#4]
we could set up a function on AWS Lambda to trigger builds on Netlify on a daily basis so the content on the site is up to date

**Comment by vormwald** [comment]
This sounds really great... I'd love to read up, if you have a post describing how to set things up, please share!

**Comment by lannonbr** [comment]
So Netlify has a page in their docs on [Webhooks](https://www.netlify.com/docs/webhooks/) so then we could write a tiny script to run daily that hits that API and triggers builds on the site

**Comment by vormwald** [comment]
an easier MVP approach to this problem: https://zapier.com/apps/netlify/integrations/schedule/29330/start-a-new-deploy-of-a-netlify-site-on-a-daily-schedule

**Comment by lannonbr** [comment]
Yeah that is what I was thinking. Zapier would work for this situation

**Comment by vormwald** [comment]
Builds are now triggered daily by zapier 👍
