### ISSUE TITLE
Need basic navigation to get around

### ISSUE THREAD

**Issue by vormwald** [syracuseio/syracuseio#7]
[syracuse.io](https://syracuse.io) has top level menu inks to the main pages: `Groups`, `Resources`, `Community`. There's value in pulling this into the site early to get around easily and see how the pages render as we make changes

Howto: https://www.gatsbyjs.org/docs/centralizing-your-sites-navigation/

**Comment by lannonbr** [comment]
Yeah It should be fairly easy to push a PR that adds a <nav> element to the header so all of the main links are available on every page
