### ISSUE TITLE
Display meetup links on group pages

### ISSUE THREAD

**Issue by peterbsmith2** [syracuseio/syracuseio#74]
I want to share the groups page. Being the best means being the best. The page is now the one stop location for groups I would point anyone to. It doesn't include a way to know what is upcoming in the community. until issue #22 is live we can add a direct link to the meetup page.

**Comment by peterbsmith2** [comment]
Link: https://www.meetup.com/Syracuse-Software-Development-Meetup

**Comment by lannonbr** [comment]
I'll tackle this tonight
