### ISSUE TITLE
Script 404 Error: https://syracuseio.now.sh/slackin.js?large

### ISSUE THREAD

**Issue by SE-Sam** [syracuseio/syracuseio#82]
Right after "our local slack group" there's a script with the link to https://syracuseio.now.sh/slackin.js?large - This seems to throw 404 errors in both Chrome and Firefox dev tools

![image](https://user-images.githubusercontent.com/16293769/55156848-5d2d2d80-5131-11e9-8846-3630b7cdf2c4.png)
---
![image](https://user-images.githubusercontent.com/16293769/55157068-e6dcfb00-5131-11e9-836e-0c1c279ba255.png)
---

**Comment by lannonbr** [comment]
I think this was for the previous site so I'll just remove the markup
